---
apiVersion: v1
kind: Service
metadata:
  name: ms-mapa-api
spec:
  type: ClusterIP
  selector:
    app: ms-mapa-api
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080